// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpecialLibrary.Context;

#nullable disable

namespace SpecialLibrary.Context.Migrations
{
    [DbContext(typeof(SpecialLibraryDbContext))]
    [Migration("20230402103514_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("SpecialLibrary.Models.OrderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2380),
                            IsAwarded = false,
                            Location = "Order Location 1",
                            SecurityLevel = 1,
                            Title = "Order1",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2395),
                            IsAwarded = false,
                            Location = "Order Location 2",
                            SecurityLevel = 1,
                            Title = "Order2",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2398),
                            IsAwarded = false,
                            Location = "Order Location 3",
                            SecurityLevel = 0,
                            Title = "Order3",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2400),
                            IsAwarded = false,
                            Location = "Order Location 4",
                            SecurityLevel = 1,
                            Title = "Order4",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2402),
                            IsAwarded = false,
                            Location = "Order Location 5",
                            SecurityLevel = 0,
                            Title = "Order5",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2405),
                            IsAwarded = false,
                            Location = "Order Location 6",
                            SecurityLevel = 1,
                            Title = "Order6",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2407),
                            IsAwarded = false,
                            Location = "Order Location 7",
                            SecurityLevel = 0,
                            Title = "Order7",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2409),
                            IsAwarded = false,
                            Location = "Order Location 8",
                            SecurityLevel = 1,
                            Title = "Order8",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2434),
                            IsAwarded = false,
                            Location = "Order Location 9",
                            SecurityLevel = 0,
                            Title = "Order9",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2438),
                            IsAwarded = false,
                            Location = "Order Location 10",
                            SecurityLevel = 0,
                            Title = "Order10",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2440),
                            IsAwarded = false,
                            Location = "Order Location 11",
                            SecurityLevel = 0,
                            Title = "Order11",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2442),
                            IsAwarded = false,
                            Location = "Order Location 12",
                            SecurityLevel = 0,
                            Title = "Order12",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2444),
                            IsAwarded = false,
                            Location = "Order Location 13",
                            SecurityLevel = 0,
                            Title = "Order13",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2445),
                            IsAwarded = false,
                            Location = "Order Location 14",
                            SecurityLevel = 1,
                            Title = "Order14",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2447),
                            IsAwarded = false,
                            Location = "Order Location 15",
                            SecurityLevel = 0,
                            Title = "Order15",
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2449),
                            IsAwarded = false,
                            Location = "Order Location 16",
                            SecurityLevel = 0,
                            Title = "Order16",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2451),
                            IsAwarded = false,
                            Location = "Order Location 17",
                            SecurityLevel = 0,
                            Title = "Order17",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2454),
                            IsAwarded = false,
                            Location = "Order Location 18",
                            SecurityLevel = 1,
                            Title = "Order18",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2456),
                            IsAwarded = false,
                            Location = "Order Location 19",
                            SecurityLevel = 1,
                            Title = "Order19",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2458),
                            IsAwarded = false,
                            Location = "Order Location 20",
                            SecurityLevel = 1,
                            Title = "Order20",
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2459),
                            IsAwarded = false,
                            Location = "Order Location 21",
                            SecurityLevel = 1,
                            Title = "Order21",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2461),
                            IsAwarded = false,
                            Location = "Order Location 22",
                            SecurityLevel = 1,
                            Title = "Order22",
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2462),
                            IsAwarded = false,
                            Location = "Order Location 23",
                            SecurityLevel = 1,
                            Title = "Order23",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2465),
                            IsAwarded = false,
                            Location = "Order Location 24",
                            SecurityLevel = 0,
                            Title = "Order24",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2467),
                            IsAwarded = false,
                            Location = "Order Location 25",
                            SecurityLevel = 1,
                            Title = "Order25",
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2468),
                            IsAwarded = false,
                            Location = "Order Location 26",
                            SecurityLevel = 0,
                            Title = "Order26",
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2470),
                            IsAwarded = false,
                            Location = "Order Location 27",
                            SecurityLevel = 1,
                            Title = "Order27",
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2472),
                            IsAwarded = false,
                            Location = "Order Location 28",
                            SecurityLevel = 0,
                            Title = "Order28",
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2474),
                            IsAwarded = false,
                            Location = "Order Location 29",
                            SecurityLevel = 1,
                            Title = "Order29",
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2023, 4, 2, 13, 35, 14, 737, DateTimeKind.Local).AddTicks(2476),
                            IsAwarded = false,
                            Location = "Order Location 30",
                            SecurityLevel = 0,
                            Title = "Order30",
                            Type = 1
                        });
                });

            modelBuilder.Entity("SpecialLibrary.Models.OrderInfoUser", b =>
                {
                    b.Property<int>("OrderInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderInfoId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderInfoUsers");
                });

            modelBuilder.Entity("SpecialLibrary.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLibraryWorker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsLibraryWorker = false,
                            Name = "User1"
                        },
                        new
                        {
                            Id = 2,
                            IsLibraryWorker = true,
                            Name = "User2"
                        },
                        new
                        {
                            Id = 3,
                            IsLibraryWorker = false,
                            Name = "User3"
                        },
                        new
                        {
                            Id = 4,
                            IsLibraryWorker = true,
                            Name = "User4"
                        },
                        new
                        {
                            Id = 5,
                            IsLibraryWorker = false,
                            Name = "User5"
                        });
                });

            modelBuilder.Entity("SpecialLibrary.Models.OrderInfoUser", b =>
                {
                    b.HasOne("SpecialLibrary.Models.OrderInfo", "OrderInfo")
                        .WithMany("OrderInfoUsers")
                        .HasForeignKey("OrderInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecialLibrary.Models.User", "User")
                        .WithMany("OrderInfoUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpecialLibrary.Models.OrderInfo", b =>
                {
                    b.Navigation("OrderInfoUsers");
                });

            modelBuilder.Entity("SpecialLibrary.Models.User", b =>
                {
                    b.Navigation("OrderInfoUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
